#Personalización MiniWindows
#Mon Sep 14 14:00:55 CST 2026
ruta=C\:\\Users\\nosoy\\OneDrive\\Documentos\\NetBeansProjects\\MiniWindowsProyecto2\\Z\\admin\\Mis Im\u00E1genes\\FondoEscritorio_1789416055905.jpg
tipo=imagen
