#Personalización MiniWindows
#Mon Sep 14 15:47:56 CST 2026
ruta=C\:\\Users\\nosoy\\OneDrive\\Documentos\\NetBeansProjects\\MiniWindowsProyecto2\\Z\\admin\\Mis Im\u00E1genes\\FondoEscritorio_1789422476396.jpg
tipo=imagen
